config/routes.rb
RecipeManager::Application.routes.draw do
  get "home/index"

  resources :recipes

  root :to => 'home#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :ingredients, :instructions, :title, :image_link
	has_attached_file :image_link, :styles => {:medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
	def resolve_image_link(link_root)
		"file:///C:/Users/jthoma20/Pictures/recipe_manager_images/"+link_root
	end
end

app/views/home/index.html.erb
<h1>Recipe Manager Home</h1>
<%= link_to "Recipe List", recipes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header">
		<div class="content">
			<h1>The Most Awesome Recipe Manager!</h1>
			<div class="nav">

				<ul>
					<li>
					<%= link_to "Home", root_path %>
					</li>

				</ul>
			</div>
		</div>
	</div>

	<div id="wrapper">

		<%= yield %>

	</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br />
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :image_link %><br />
    <%= f.text_field :image_link %>
  </div>
	<div class="field">
		<br/>
		<%= image_tag @recipe.image_link.url(:medium) %>
		<br/>
		<%= f.file_field :image_link %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h2>Listing recipes</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Ingredients</th>
    <th>Instructions</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
	<tr class="<%= cycle('even','odd') -%>">
    <td><%= recipe.title %></td>
    <td><%= recipe.ingredients %></td>
    <td><%= recipe.instructions %></td>
		<td><%= image_tag recipe.image_link.url(:thumb) %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p id="title">
  <b>Title:</b>
  <%= @recipe.title %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @recipe.ingredients %>
</p>

<p>
  <b>Instructions:</b>
  <%= @recipe.instructions %>
</p>

<p>
  <b>Image:</b>
	<%= image_tag @recipe.image_link.url(:medium) %>
	<%#<%= link_to @recipe.image_link, "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR--xISsvmL9BCb0xZiX6526ND2SgdoOuI-iGr5UkYhZPCGMIIUyQ" %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>